import json
from typing import Any, Dict, Optional

from app.ai.client import client, MODEL_DEPLOYMENT


FINAL_AGENT_INSTRUCTIONS = """
You are the final reporting agent for an AI-powered YouTube Growth & Spike Analyzer.

Your job is to transform structured quantitative analysis, research findings,
audience signals, cross-year analysis, and thumbnail analysis into a clear,
evidence-backed growth case study.

You are NOT the research agent.

The research agent gathers evidence.
The Python analysis computes quantitative signals.
You synthesize these into the final user-facing report.

==================================================
CORE RULES
==================================================

1. NEVER invent facts, sources, statistics, events, or explanations.

2. Distinguish clearly between:
   - DIRECT
   - INDIRECT
   - AUDIENCE_SAMPLE
   - HYPOTHESIS

3. Use confidence levels:
   - HIGH
   - MEDIUM
   - LOW

4. Do not turn correlation into causation.

For example:

BAD:
"The new thumbnail caused the video to go viral."

GOOD:
"The thumbnail was visually different from the surrounding thumbnails.
This coincided with the spike, but the available evidence does not establish
that the thumbnail caused the increase in views."

5. If the research explicitly says causal evidence was not found,
preserve that limitation.

6. Quantitative calculations generated by the system are INTERNAL_ANALYSIS.
They are not external sources.

7. External claims should retain their source information whenever provided.

8. If something is unknown, say that it is unknown.

9. Do not fill missing evidence with assumptions.

10. Recommendations must be framed as experiments or evidence-based actions,
not guarantees.

11. Thumbnail analysis describes visual characteristics only.
It does NOT establish that a thumbnail caused growth.

12. Audience comment analysis is a sample signal.
Do not describe it as representative of the entire audience unless the
provided evidence explicitly supports that claim.

13. Cross-year candidates are candidates for investigation.
Do not claim that they caused the target event unless evidence explicitly
supports that conclusion.

==================================================
REPORTING STYLE
==================================================

The report should answer:

- What happened?
- What changed around the spike?
- What was different from the previous content?
- What happened immediately afterward?
- What audience signals appeared?
- What patterns exist across years?
- What visual/thumbnail changes occurred?
- Which mechanisms are supported by evidence?
- What remains uncertain?
- What could a creator test based on these findings?

Keep factual observations separate from interpretation.

Use concise explanations, but preserve important evidence.

==================================================
EVIDENCE LEVELS
==================================================

DIRECT:
The provided data or source directly establishes the statement.

INDIRECT:
The evidence supports the interpretation but does not directly establish it.

AUDIENCE_SAMPLE:
The statement comes from the analyzed comments/audience sample.

HYPOTHESIS:
A plausible explanation that has not been established by the evidence.

==================================================
CONFIDENCE
==================================================

HIGH:
Strong direct evidence or multiple independent signals.

MEDIUM:
Several supporting signals exist, but causality or completeness is uncertain.

LOW:
Weak, incomplete, or indirect evidence.

==================================================
SOURCES
==================================================

Preserve source URLs/titles supplied by the research system.

For internal calculations, use:

{
    "type": "INTERNAL_ANALYSIS",
    "description": "Calculated from the creator's YouTube dataset"
}

Do not fabricate URLs.

==================================================
OUTPUT
==================================================

Return ONLY valid JSON.

Use exactly this top-level structure:

{
  "creator": "",
  "event": {
    "title": "",
    "date": "",
    "views": 0,
    "spike_ratio": 0,
    "event_type": ""
  },

  "executive_summary": "",

  "growth_story": {
    "before": "",
    "trigger_event": "",
    "after": "",
    "long_term_effect": ""
  },

  "what_changed": [
    {
      "factor": "",
      "evidence_level": "DIRECT",
      "confidence": "HIGH",
      "explanation": "",
      "evidence": []
    }
  ],

  "thumbnail_insights": {
    "before": "",
    "target": "",
    "after": "",
    "visual_patterns": [
      {
        "pattern": "",
        "evidence_level": "DIRECT",
        "confidence": "HIGH",
        "explanation": ""
      }
    ]
  },

  "audience_insights": [
    {
      "insight": "",
      "evidence_level": "AUDIENCE_SAMPLE",
      "confidence": "MEDIUM",
      "explanation": "",
      "evidence": []
    }
  ],

  "cross_year_insights": [
    {
      "insight": "",
      "evidence_level": "DIRECT",
      "confidence": "MEDIUM",
      "explanation": "",
      "evidence": []
    }
  ],

  "growth_mechanisms": [
    {
      "mechanism": "",
      "status": "SUPPORTED_INTERPRETATION",
      "confidence": "MEDIUM",
      "evidence": [],
      "explanation": ""
    }
  ],

  "what_is_unknown": [
    ""
  ],

  "lessons": [
    ""
  ],

  "actionable_roadmap": [
    {
      "action": "",
      "reason": "",
      "evidence": [],
      "expected_signal": ""
    }
  ],

  "experiments_to_run": [
    {
      "experiment": "",
      "hypothesis": "",
      "measurement": ""
    }
  ],

  "sources": [
    {
      "type": "",
      "title": "",
      "url": "",
      "description": ""
    }
  ]
}

==================================================
IMPORTANT INTERPRETATION RULES
==================================================

A spike in views is an observation.

A change in content is an observation.

A change in thumbnail design is an observation.

A comment pattern is an audience sample signal.

A relationship between those observations is an interpretation.

A claim that one caused another is causal and requires evidence.

If causal evidence is absent, explicitly say so.

When making recommendations, derive them from observed patterns rather than
pretending that the observed pattern guarantees future success.

Do not rank or score strategies unless the input data explicitly contains
such quantitative measurements and the ranking is necessary to faithfully
report the analysis.

Return JSON only.
"""


def _safe_json(value: Any) -> str:
    """
    Convert arbitrary Python data into compact JSON for the prompt.
    """
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            default=str
        )
    except (TypeError, ValueError):
        return json.dumps(str(value), ensure_ascii=False)


def _extract_json(text: str) -> Dict[str, Any]:
    """
    Extract JSON from the model response.

    Handles:
    - pure JSON
    - ```json ... ```
    - accidental surrounding text
    """

    text = text.strip()

    # Normal JSON
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Markdown code block
    if text.startswith("```"):
        lines = text.splitlines()

        if len(lines) >= 3:
            if lines[0].strip().lower() in ("```json", "```"):
                if lines[-1].strip() == "```":
                    cleaned = "\n".join(lines[1:-1])

                    try:
                        return json.loads(cleaned)
                    except json.JSONDecodeError:
                        pass

    # Attempt to find the outermost JSON object
    start = text.find("{")
    end = text.rfind("}")

    if start != -1 and end != -1 and end > start:
        candidate = text[start:end + 1]

        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass

    raise ValueError(
        f"Final agent returned invalid JSON:\n{text}"
    )


def _normalise_event(event: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Normalize the target event before sending it to the final agent.
    """
    if not event:
        return {}

    return {
        "title": event.get("title"),
        "date": event.get("date")
            or event.get("published_at"),
        "views": event.get("views"),
        "spike_ratio": event.get("spike_ratio"),
        "robust_z": event.get("robust_z"),
        "event_type": event.get("event_type")
            or event.get("classification")
            or event.get("type"),
        "video_id": event.get("video_id")
            or event.get("id"),
    }


def _build_prompt(
    creator: str,
    event: Dict[str, Any],
    quantitative_analysis: Optional[Dict[str, Any]] = None,
    research: Optional[Dict[str, Any]] = None,
    audience_analysis: Optional[Dict[str, Any]] = None,
    cross_year_analysis: Optional[Any] = None,
    thumbnail_analysis: Optional[Any] = None,
) -> str:

    quantitative_analysis = quantitative_analysis or {}
    research = research or {}
    audience_analysis = audience_analysis or {}

    prompt = f"""
Create the final growth-analysis report for this creator.

CREATOR
-------
{creator}

TARGET EVENT
------------
{_safe_json(_normalise_event(event))}


QUANTITATIVE ANALYSIS
---------------------
{_safe_json(quantitative_analysis)}


RESEARCH AGENT OUTPUT
---------------------
{_safe_json(research)}


AUDIENCE ANALYSIS
-----------------
{_safe_json(audience_analysis)}


CROSS-YEAR ANALYSIS
-------------------
{_safe_json(cross_year_analysis)}


THUMBNAIL ANALYSIS
------------------
{_safe_json(thumbnail_analysis)}


FINAL REPORT REQUIREMENTS
-------------------------

1. Start by explaining the observed growth event.

2. Describe the content immediately before the event.

3. Describe what changed at the target event.

4. Describe what happened immediately afterward.

5. Explain longer-term effects only when supported by the supplied data.

6. Use the thumbnail analysis to describe visual changes.

7. Use audience comments only as an audience-sample signal.

8. Use cross-year candidates as evidence for patterns worth investigating,
   not as proof of causality.

9. Identify potential growth mechanisms.

10. Explicitly separate:
    - observed evidence
    - interpretation
    - hypothesis

11. Include unknowns and limitations.

12. Produce practical creator experiments based on the evidence.

13. Do not claim that any individual factor caused the spike unless the
    supplied research contains direct evidence establishing causality.

14. Do not invent sources.

15. Do not omit important limitations from the research agent.

16. Return ONLY valid JSON using the required schema.
"""

    return prompt


def _validate_report(report: Dict[str, Any]) -> Dict[str, Any]:
    """
    Lightweight structural validation.

    We intentionally do not force every nested field because the model may
    return an empty list when the supplied evidence does not support a section.
    """

    required_fields = [
        "creator",
        "event",
        "executive_summary",
        "growth_story",
        "what_changed",
        "thumbnail_insights",
        "audience_insights",
        "cross_year_insights",
        "growth_mechanisms",
        "what_is_unknown",
        "lessons",
        "actionable_roadmap",
        "experiments_to_run",
        "sources",
    ]

    missing = [
        field
        for field in required_fields
        if field not in report
    ]

    if missing:
        raise ValueError(
            "Final report is missing required fields: "
            + ", ".join(missing)
        )

    return report


def generate_final_report(
    creator: str,
    event: Dict[str, Any],
    quantitative_analysis: Optional[Dict[str, Any]] = None,
    research: Optional[Dict[str, Any]] = None,
    audience_analysis: Optional[Dict[str, Any]] = None,
    cross_year_analysis: Optional[Any] = None,
    thumbnail_analysis: Optional[Any] = None,
) -> Dict[str, Any]:
    """
    Generate the final user-facing growth report.

    Parameters
    ----------
    creator:
        Creator/channel name.

    event:
        Target spike event.

    quantitative_analysis:
        Python-generated metrics and spike information.

    research:
        Output from app.research.agent.research_event().

    audience_analysis:
        Audience/comment analysis.

    cross_year_analysis:
        Deterministic cross-year candidate analysis.

    thumbnail_analysis:
        Output from thumbnail event analysis.

    Returns
    -------
    dict
        Structured final report.
    """

    prompt = _build_prompt(
        creator=creator,
        event=event,
        quantitative_analysis=quantitative_analysis,
        research=research,
        audience_analysis=audience_analysis,
        cross_year_analysis=cross_year_analysis,
        thumbnail_analysis=thumbnail_analysis,
    )

    response = client.responses.create(
        model=MODEL_DEPLOYMENT,
        instructions=FINAL_AGENT_INSTRUCTIONS,
        input=prompt,
    )

    output_text = response.output_text

    report = _extract_json(output_text)

    return _validate_report(report)